// <auto-generated />
using System;
using Barbearia.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Barbearia.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260808135442_ProdutosEPermissoes")]
    partial class ProdutosEPermissoes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Barbearia.Domain.Entities.Agendamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BarbeiroId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CanceladoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FimUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InicioUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Origem")
                        .HasColumnType("integer");

                    b.Property<Guid>("ServicoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServicoId");

                    b.HasIndex("BarbeiroId", "InicioUtc");

                    b.HasIndex("ClienteId", "InicioUtc");

                    b.ToTable("agendamentos", (string)null);
                });

            modelBuilder.Entity("Barbearia.Domain.Entities.Barbeiro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Atende")
                        .HasColumnType("boolean");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer");

                    b.Property<bool>("PodeGerenciarClientes")
                        .HasColumnType("boolean");

                    b.Property<bool>("PodeGerenciarProdutos")
                        .HasColumnType("boolean");

                    b.Property<bool>("PodeGerenciarServicos")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrecisaTrocarSenha")
                        .HasColumnType("boolean");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("barbeiros", (string)null);
                });

            modelBuilder.Entity("Barbearia.Domain.Entities.Bloqueio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BarbeiroId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FimUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InicioUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("BarbeiroId", "InicioUtc", "FimUtc");

                    b.ToTable("bloqueios", (string)null);
                });

            modelBuilder.Entity("Barbearia.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Telefone")
                        .IsUnique();

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("Barbearia.Domain.Entities.Configuracao", b =>
                {
                    b.Property<string>("Chave")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("AtualizadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Secreto")
                        .HasColumnType("boolean");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Chave");

                    b.ToTable("configuracoes", (string)null);
                });

            modelBuilder.Entity("Barbearia.Domain.Entities.ConversaEstado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiraEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PropostaBarbeiroId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PropostaInicioUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PropostaServicoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("conversa_estados", (string)null);
                });

            modelBuilder.Entity("Barbearia.Domain.Entities.Expediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BarbeiroId")
                        .HasColumnType("uuid");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("HoraFim")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BarbeiroId", "DiaSemana");

                    b.ToTable("expedientes", (string)null);
                });

            modelBuilder.Entity("Barbearia.Domain.Entities.MagicLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiraEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UsadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("magic_links", (string)null);
                });

            modelBuilder.Entity("Barbearia.Domain.Entities.MensagemProcessada", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("ProcessadaEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProcessadaEmUtc");

                    b.ToTable("mensagens_processadas", (string)null);
                });

            modelBuilder.Entity("Barbearia.Domain.Entities.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int>("Estoque")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("PrecoCentavos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("produtos", (string)null);
                });

            modelBuilder.Entity("Barbearia.Domain.Entities.Servico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("PrecoCentavos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("servicos", (string)null);
                });

            modelBuilder.Entity("Barbearia.Domain.Entities.Agendamento", b =>
                {
                    b.HasOne("Barbearia.Domain.Entities.Barbeiro", "Barbeiro")
                        .WithMany("Agendamentos")
                        .HasForeignKey("BarbeiroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Barbearia.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Agendamentos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Barbearia.Domain.Entities.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Barbeiro");

                    b.Navigation("Cliente");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("Barbearia.Domain.Entities.Bloqueio", b =>
                {
                    b.HasOne("Barbearia.Domain.Entities.Barbeiro", "Barbeiro")
                        .WithMany("Bloqueios")
                        .HasForeignKey("BarbeiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barbeiro");
                });

            modelBuilder.Entity("Barbearia.Domain.Entities.ConversaEstado", b =>
                {
                    b.HasOne("Barbearia.Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Barbearia.Domain.Entities.Expediente", b =>
                {
                    b.HasOne("Barbearia.Domain.Entities.Barbeiro", "Barbeiro")
                        .WithMany("Expedientes")
                        .HasForeignKey("BarbeiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barbeiro");
                });

            modelBuilder.Entity("Barbearia.Domain.Entities.MagicLink", b =>
                {
                    b.HasOne("Barbearia.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Barbearia.Domain.Entities.Barbeiro", b =>
                {
                    b.Navigation("Agendamentos");

                    b.Navigation("Bloqueios");

                    b.Navigation("Expedientes");
                });

            modelBuilder.Entity("Barbearia.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Agendamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
